[package]
name = "iota-bindings"
version = "0.1.0"
authors = ["Andreas C. Osowski <andreas@osowski.de>"]
keywords = ["no_std"]

[lib]
path = "src/lib.rs"
test = true
doc = true

[[bin]]
name = "iota_bindings"
path = "src/main.rs"
doc = false
test = false

[features]
default = []

[dependencies]
iota-trytes = { path = "../trytes", features = ["alloc"] }
iota-curl = { path = "../curl" }
iota-curl-cpu = { path = "../curl-cpu" }
iota-sign = { path = "../sign" }

cty = { git = "https://github.com/japaric/cty.git" }


